import { SessionMethodType } from "../../../redux/session/types";

export const METHODS: SessionMethodType[] = [
    {
        label: "5m",
        name: "Just 5",
        minutes: 5,
        shortBreak: 5,
        hasLongBreak: false,
        longBreak: undefined,
        longBreakInterval: undefined,
        type: "timer",
    },
    {
        label: "25",
        name: "Pomodoro",
        minutes: 25,
        shortBreak: 5,
        hasLongBreak: true,
        longBreak: 15,
        longBreakInterval: 5,
        type: "timer",
    },
    {
        label: "90",
        name: "Ultradian Rythm",
        minutes: 90,
        shortBreak: 30,
        hasLongBreak: false,
        longBreak: undefined,
        longBreakInterval: undefined,
        type: "timer",
    },
    {
        label: " \u221E",
        name: "Stopwatch",
        minutes: 0,
        shortBreak: 5,
        hasLongBreak: false,
        longBreak: undefined,
        longBreakInterval: undefined,
        type: "stopwatch",
    },
    {
        label: "18",
        name: "Custom 1",
        minutes: 18,
        shortBreak: 5,
        hasLongBreak: false,
        longBreak: undefined,
        longBreakInterval: undefined,
        type: "timer",
    },
    {
        label: "19",
        name: "Custom 2",
        minutes: 19,
        shortBreak: 5,
        hasLongBreak: false,
        longBreak: undefined,
        longBreakInterval: undefined,
        type: "timer",
    },
    {
        label: "20",
        name: "Custom 3",
        minutes: 20,
        shortBreak: 5,
        hasLongBreak: false,
        longBreak: undefined,
        longBreakInterval: undefined,
        type: "timer",
    },
    {
        label: "21",
        name: "Custom 4",
        minutes: 21,
        shortBreak: 5,
        hasLongBreak: false,
        longBreak: undefined,
        longBreakInterval: undefined,
        type: "timer",
    },
    {
        label: "22",
        name: "Custom 5",
        minutes: 22,
        shortBreak: 5,
        hasLongBreak: false,
        longBreak: undefined,
        longBreakInterval: undefined,
        type: "timer",
    },
    {
        label: "23",
        name: "Custom 6",
        minutes: 23,
        shortBreak: 5,
        hasLongBreak: false,
        longBreak: undefined,
        longBreakInterval: undefined,
        type: "timer",
    },
];
