# Node.js with React

resources:
- repo: self
  fetchDepth: 1
queue:
  name: Hosted Ubuntu 1604

trigger:
- master
variables:
  DockerImageName: 'gamitude/web'


steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'docker build -f Dockerfile -t $DockerImageName:latest .'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: docker save --output $(build.artifactstagingdirectory)/gamitude_web.tar $DockerImageName'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)/gamitude_web.tar'