# build environment
FROM node:13.12.0-alpine as build
WORKDIR /app
ARG BROWSER_ARG
ARG REACT_APP_API_ENDPOINT_ARG
ENV BROWSER=$BROWSER_ARG
ENV REACT_APP_API_ENDPOINT=$REACT_APP_API_ENDPOINT_ARG
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./
COPY package-lock.json ./
RUN npm ci --silent
RUN npm install react-scripts@3.4.1 -g --silent
COPY . ./
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY ./default.conf /etc/nginx/conf.d/default.conf
CMD ["/bin/sh", "-c", "exec nginx -g 'daemon off;';"]