export const ProjectsActionTypes = {
    SET_BOOSTED: "SET_BOOSTED",
    SET_DOMINANT: "SET_DOMINANT",
    SET_NAME: "SET_NAME",
    SET_METHOD: "SET_METHOD",
    SET_BREAK_IN_PROGRESS: "SET_BREAK_IN_PROGRESS",
    SET_SESSION_IN_PROGRESS: "SET_SESSION_IN_PROGRESS",
    SET_SESSIONS_COMPLETE: "SET_SESSIONS_COMPLETE",
    SET_STATUS: "SET_STATUS",
    ADD_PROJECT: "ADD_PROJECT",
};
