export const ProjectsActionTypes = {
    SET_PROJECTS: "SET_PROJECTS",
    SET_BOOSTED: "SET_BOOSTED",
    SET_DOMINANT: "SET_DOMINANT",
    SET_NAME: "SET_NAME",
    SET_METHOD: "SET_METHOD",
    SET_STATUS: "SET_STATUS",
    ADD_PROJECT: "ADD_PROJECT",
    DELETE_PROJECT: "DELETE_PROJECT",
    SET_SELECTED_PROJECT: "SET_SELECTED_PROJECT",
};
