export const FoldersActionTypes = {
    ADD_FOLDER: "ADD_FOLDER",
    SET_FOLDERS: "SET_FOLDERS",
    SET_SELECTED_FOLDER: "SET_SELECTED_FOLDER",
    SET_SELECTED_FOLDER_BY_ID: "SET_SELECTED_FOLDER_BY_ID",
};
