export const TimersActionTypes = {
    SET_SELECTED_TIMER: "SET_SELECTED_TIMER",
    ADD_TIMER: "ADD_TIMER",
    SET_TIMERS: "SET_TIMERS",
    SET_SELECTED_TIMER_BY_ID: "SET_SELECTED_TIMER_BY_ID",
};
