export const AUTH_LOGIN_REQUEST = "AUTH-LOGIN-REQUEST";
export const AUTH_LOGIN_SUCCESS = "AUTH-LOGIN-SUCCESS";
export const AUTH_LOGIN_FAILED = "AUTH-LOGIN-FAILED";
export const AUTH_LOGOUT = "AUTH-LOGOUT";

export const AUTH_REGISTER_SUCCESS = "AUTH-REGISTER-SUCCESS";
export const AUTH_REGISTER_FAILED = "AUTH-REGISTER-FAILED";

export const AUTH_UPDATE_PROFILE = "AUTH-UPDATE-PROFILE";
// Authentication states
export const AUTH_UNKNOWN = "AUTH-UNKNOWN";
export const AUTH_LOGGED_IN = "AUTH-LOGGED-IN";
export const AUTH_LOGGED_OUT = "AUTH-LOGGED-OUT";
// User profile
export const USER_FETCH_REQUEST = "USER-FETCH-REQUEST";
export const USER_FETCH_SUCCESS = "USER-FETCH-SUCCESS";
export const USER_FETCH_FAILED = "USER-FETCH-FAILED";
