export const SessionActionTypes = {
    SET_SESSION_IN_PROGRESS: "SET_SESSION_IN_PROGRESS",
    SET_SESSIONS_COMPLETE: "SET_SESSIONS_COMPLETE",
    SET_SESSION_TYPE: "SET_SESSION_TYPE",
    SET_SESSION_METHOD: "SET_SESSION_METHOD",
};
