export const SessionActionTypes = {
    SET_BREAK_IN_PROGRESS: "SET_BREAK_IN_PROGRESS",
    SET_SESSION_IN_PROGRESS: "SET_SESSION_IN_PROGRESS",
    SET_SESSIONS_COMPLETE: "SET_SESSIONS_COMPLETE",
    SET_BREAK_TIME: "SET_BREAK_TIME",
    SET_PROJECTS_TAB: "SET_PROJECTS_TAB",
};
