export const DialogActionTypes = {
    SET_FOLDERS_SETTINGS_DIALOG_OPEN: "SET_FOLDERS_SETTINGS_DIALOG_OPEN",
    SET_ADD_PROJECT_DIALOG_OPEN: "SET_ADD_PROJECT_DIALOG_OPEN",
    SET_TIMER_SETTINGS_DIALOG_OPEN: "SET_TIMER_SETTINGS_DIALOG_OPEN",
};
